name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        **Looking forward for reporting a security issue:**
        Please report security issues by following our security policy: https://contribute.freecodecamp.org/security

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected to see!
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop images here or paste them
    validations:
      required: false

  - type: input
    id: desktop-os
    attributes:
      label: Desktop OS
      description: What operating system are you using?
      placeholder: e.g. iOS, Windows 10, Ubuntu 20.04
    validations:
      required: false

  - type: input
    id: desktop-browser
    attributes:
      label: Desktop Browser
      description: What browser are you using?
      placeholder: e.g. chrome, safari, firefox
    validations:
      required: false

  - type: input
    id: desktop-version
    attributes:
      label: Desktop Browser Version
      description: What version of the browser are you using?
      placeholder: e.g. 22, 95, 120
    validations:
      required: false

  - type: input
    id: mobile-device
    attributes:
      label: Mobile Device
      description: What mobile device are you using?
      placeholder: e.g. iPhone6, Samsung Galaxy S21
    validations:
      required: false

  - type: input
    id: mobile-os
    attributes:
      label: Mobile OS
      description: What mobile operating system are you using?
      placeholder: e.g. iOS8.1, Android 11
    validations:
      required: false

  - type: input
    id: mobile-browser
    attributes:
      label: Mobile Browser
      description: What mobile browser are you using?
      placeholder: e.g. stock browser, safari, chrome
    validations:
      required: false

  - type: input
    id: mobile-version
    attributes:
      label: Mobile Browser Version
      description: What version of the mobile browser are you using?
      placeholder: e.g. 22, 95, 120
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: Any other details that might help us understand the issue
    validations:
      required: false
