name: Feature Request
description: Request a new feature or enhancement
title: "[Feature]: "
labels: ["type: feature request", "status: waiting triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you'd like to see.
      placeholder: Tell us about your feature idea!
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Is this related to a problem?
      description: Is there a problem this feature would solve? Describe it here.
      placeholder: e.g. I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you've thought about.
      placeholder: What else could work?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about this feature.
      placeholder: Any other details that might help us understand your idea
    validations:
      required: false
